# Generated by Django 3.0.5 on 2020-04-25 01:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(verbose_name='具体描述'),
        ),
    ]
