# Generated by Django 3.0.5 on 2020-05-02 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0002_auto_20200425_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qas_system.Question', verbose_name='问题'),
        ),
    ]
