# Generated by Django 3.0.5 on 2020-05-02 07:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0003_auto_20200502_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', ckeditor.fields.RichTextField(verbose_name='举报理由')),
                ('tip_date', models.DateTimeField(auto_now=True, verbose_name='举报时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoffs', to='qas_system.Question', verbose_name='问题')),
            ],
            options={
                'ordering': ('tip_date',),
            },
        ),
    ]
