# Generated by Django 3.0.5 on 2020-05-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0006_auto_20200504_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='年级'),
        ),
    ]
