# Generated by Django 3.0.5 on 2020-05-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0007_auto_20200504_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='qas_system.User', verbose_name='评论者'),
            preserve_default=False,
        ),
    ]
