# Generated by Django 3.0.5 on 2020-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0008_comment_comment_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='用户名'),
        ),
    ]
