# Generated by Django 3.0.5 on 2020-05-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0009_auto_20200505_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qas_system.User', verbose_name='评论者'),
        ),
    ]
