# Generated by Django 3.0.5 on 2020-05-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0014_auto_20200506_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoff',
            name='tipoff_person',
        ),
    ]
