# Generated by Django 3.0.5 on 2020-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0017_user_collect_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='page_views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
