# Generated by Django 3.0.5 on 2020-05-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0018_auto_20200511_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='qas_system.User', verbose_name='点赞者')),
                ('good_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='qas_system.Question', verbose_name='问题')),
            ],
        ),
    ]
