# Generated by Django 3.0.5 on 2020-05-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qas_system', '0019_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cgood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgoods', to='qas_system.User', verbose_name='点赞者')),
                ('good_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgoods', to='qas_system.Comment', verbose_name='评论')),
            ],
        ),
    ]
